#####################################################################################################
# SPLINE LEVEL SETUP FILE - Created by Derek Ward.
#
# Splines loaded for a level are put in here, with setting for the type of spline, and its duration.
#
# The RECORD name should tie up with a filename in your level\spl\directory
# However you should not add .spl to the end of the filename!
#
# The default duration can be specified here for testing, but this can be overridden permentantly by 
# a script if not 0.0f.
#
#####################################################################################################

# Put comments here to describe what the spline does or is intended for.
#STARTCODE <--- NEVER REMOVE THIS AS THIS INDICATES WHERE A SPLINE FILE SHOULD START FOR BINARTY CONCATENATION.
RECORD	FOLLOW1
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		13.0
END

RECORD	INTRO1
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		6
END

RECORD	INTRO2
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		6
END

RECORD	INTRO3
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		6
END