#
# Weather.ini contains the fog-colours and stuff as should be used for each weather type in the game
#
####################################################################################################
RECORD CLOUDY
	FARCLIP 	200.0f
	FOGSTART	30.0f
	SKY		12,12,12
	CLOUDS		6,6,6
END
####################################################################################################
RECORD WINDY
	FARCLIP 	200.0f
	FOGSTART	30.0f
	SKY		10,10,10
	CLOUDS		7,7,7
END
###################################################################################################
RECORD RAINY
	FARCLIP 	200.0f
	FOGSTART	30.0f
	SKY		12,18,12
	CLOUDS		6,9,6
END
####################################################################################################
RECORD THUNDERSTORM
	FARCLIP 	100.0f
	FOGSTART	30.0f
	SKY		10,11,10
	CLOUDS		5,6,5
END
####################################################################################################
RECORD FOGGY
	FARCLIP 	30.0f
	FOGSTART	5.0f
	SKY		20,20,20
	CLOUDS		20,20,20
END
####################################################################################################
RECORD CLEAR
	FARCLIP 	300.0f
	FOGSTART	100.0f
	SKY		2,2,5
	CLOUDS		2,2,5
END
####################################################################################################
RECORD ARTFILTER
	ARTFILTERRAD_INDOORS	0.002f
	ARTFILTER_INDOORS		60,60,60
	ARTFILTERRAD_CLOUDY		0.002f
	ARTFILTER_CLOUDY		60,60,60
	ARTFILTERRAD_RAINY		0.002f
	ARTFILTER_RAINY			60,60,60
	ARTFILTERRAD_FOGGY		0.002f
	ARTFILTER_FOGGY			60,60,60
	ARTFILTERRAD_CLEAR		0.002f
	ARTFILTER_CLEAR			60,60,60
END



