# LevelSetup.ini
#
# Stores various values that need to be define at the start of each level.
# E.g. fog parameters, weather etc.
# Fog types: LINEAR, EXP, EXP2

RECORD levelSetup
	FOG_COLOUR		0,0,0,0
	FOG_TYPE		LINEAR
	FOG_DENSITY		1.0
	FAR_CLIP		80.0
END

