# LevelSetup.ini
#
# Stores various values that need to be define at the start of each level.
# E.g. fog parameters, weather etc.
# Fog types: LINEAR, EXP, EXP2
#
# Note: these values are assigned in order - the number in the record header is ignored!!!!!!!!



RECORD world1
	FOG_COLOUR		10,10,11,0
	FOG_TYPE		LINEAR
	FOG_DENSITY		0.01
	NEAR_CLIP		0.1
	FAR_CLIP		120.0
	AMBIENT			0, 0, 0, 0
END


####################################################################################################
RECORD fogpatches
	FOGPATCH          -172.27,-3.4,27.67, -172.2,-3.4,46.8, -213.1,-3.4,27.7, -213.1,-3.4,46.8, 200
END

####################################################################################################
RECORD CLOUDY
	FARCLIP 	200.0f
	FOGSTART	30.0f
	SKY		12,12,12
	CLOUDS		6,6,6
END
####################################################################################################
RECORD WINDY
	FARCLIP 	200.0f
	FOGSTART	30.0f
	SKY		10,10,10
	CLOUDS		7,7,7
END
###################################################################################################
RECORD RAINY
	FARCLIP 	200.0f
	FOGSTART	30.0f
	SKY		12,18,12
	CLOUDS		6,9,6
END
####################################################################################################
RECORD THUNDERSTORM
	FARCLIP 	100.0f
	FOGSTART	30.0f
	SKY		10,10,11
	CLOUDS		5,5,6
END
####################################################################################################
RECORD FOGGY
	FARCLIP 	30.0f
	FOGSTART	5.0f
	SKY		20,20,20
	CLOUDS		20,20,20
END
####################################################################################################
RECORD CLEAR
	FARCLIP 	300.0f
	FOGSTART	100.0f
	SKY		2,2,5
	CLOUDS		2,2,5
END

####################################################################################################

# this space is intentionally left blank!
