#####################################################################################################
# SPLINE LEVEL SETUP FILE - Created by Derek Ward.
#
# Splines loaded for a level are put in here, with setting for the type of spline, and its duration.
#
# The RECORD name should tie up with a filename in your level\spl\directory
# However you should not add .spl to the end of the filename!
#
# The default duration can be specified here for testing, but this can be overridden permentantly by 
# a script if not 0.0f.
#
#####################################################################################################

# Put comments here to describe what the spline does or is intended for.
#STARTCODE <--- NEVER REMOVE THIS AS THIS INDICATES WHERE A SPLINE FILE SHOULD START FOR BINARTY CONCATENATION.

RECORD	FOLLOW1
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	1
	DURATION		2.0
END

RECORD	FOLLOW2
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		8.0
END

RECORD	LOOKAT2
	ISFOLLOW		0
	ISSMOOTH		0
	ISALIGNEDFOLLOWPATH 0
	DURATION		4.0
END

RECORD	FOLLOW3
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		6.0
END

RECORD	LOOKAT3
	ISFOLLOW		0
	ISSMOOTH		0
	ISALIGNEDFOLLOWPATH 	0
	DURATION		6.0
END

RECORD	FOLLOW4
	ISFOLLOW		1
	ISSMOOTH		0
	ISALIGNEDFOLLOWPATH 	1
	DURATION		3.0

END

RECORD	START
	ISFOLLOW		1
	ISSMOOTH		0
	ISALIGNEDFOLLOWPATH 	0
	DURATION		3.5

END

RECORD	START_PAUSE
	ISFOLLOW		1
	ISSMOOTH		0
	ISALIGNEDFOLLOWPATH 	0
	DURATION		1.5

END



