# LevelSetup.ini
#
# Stores various values that need to be define at the start of each level.
# E.g. fog parameters, weather etc.
# Fog types: LINEAR, EXP, EXP2

RECORD levelSetup
	FOG_COLOUR		0,0,0,0
	FOG_TYPE		LINEAR
	FOG_DENSITY		0.01
	FAR_CLIP		100
END

####################################################################################################
RECORD CLOUDY
	AVOID
END
####################################################################################################
RECORD WINDY
	AVOID
END
###################################################################################################
RECORD RAINY
	AVOID
END
####################################################################################################
RECORD THUNDERSTORM
	AVOID
END
####################################################################################################
RECORD FOGGY
	AVOID
END
####################################################################################################
RECORD CLEAR
	FARCLIP 	100.0f
	FOGSTART	80.0f
	SKY		2,2,5
	CLOUDS		2,2,5
END
