#####################################################################################################
# SPLINE LEVEL SETUP FILE - Created by Derek Ward.
#
# Splines loaded for a level are put in here, with setting for the type of spline, and its duration.
#
# The RECORD name should tie up with a filename in your level\spl\directory
# However you should not add .spl to the end of the filename!
#
# The default duration can be specified here for testing, but this can be overridden permentantly by 
# a script if not 0.0f.
#
#####################################################################################################

# Put comments here to describe what the spline does or is intended for.
#STARTCODE <--- NEVER REMOVE THIS AS THIS INDICATES WHERE A SPLINE FILE SHOULD START FOR BINARTY CONCATENATION.
RECORD	FOLLOW1
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		4.0
END

RECORD	LOOKAT1
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	FOLLOW2
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		4.0
END

RECORD	LOOKAT2
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	FOLLOW3
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		4.0
END

RECORD	LOOKAT3
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	FOLLOW4
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		9.0
END

RECORD	LOOKAT4
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		9.0
END

RECORD	CLOSEDGATEF
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	CLOSEDGATEL
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	OPENINGGATEF
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	OPENINGGATEL
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	OPENGATEF
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	OPENGATEL
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	CHASEF
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	CHASEL
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	HIDEF
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	HIDEL
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	WALKF
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	WALKL
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	RUNF
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	RUNL
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	SWITCHF
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	SWITCHL
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	TUNNELF
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	TUNNELL
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	ROOMF
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	ROOML
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	CAMERAF
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	CAMERAPAUSE1L
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	CAMERAPANL
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	CAMERAPAUSE2L
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	CAMERAZOOMF
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	CAMERAZOOML
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	CAMERAPAUSEF
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END

RECORD	CAMERAPAUSE3L
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	0
	DURATION		5.0
END
