#####################################################################################################
# SPLINE LEVEL SETUP FILE - Created by Derek Ward.
#
# Splines loaded for a level are put in here, with setting for the type of spline, and its duration.
#
# The RECORD name should tie up with a filename in your level\spl\directory
# However you should not add .spl to the end of the filename!
#
# The default duration can be specified here for testing, but this can be overridden permentantly by 
# a script if not 0.0f.
#
#####################################################################################################

# Put comments here to describe what the spline does or is intended for.
#STARTCODE <--- NEVER REMOVE THIS AS THIS INDICATES WHERE A SPLINE FILE SHOULD START FOR BINARTY CONCATENATION.
RECORD	FOLLOW1
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	1
	DURATION		6
END

RECORD	FOLLOW2
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	1
	DURATION		6
END

RECORD	FOLLOW3
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	1
	DURATION		4
END

RECORD	FOLLOW4
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	1
	DURATION		4
END

RECORD	FOLLOW5
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	1
	DURATION		4
END

RECORD	SNIPER1F
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	1
	DURATION		7
END

RECORD	SNIPER1L
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	1
	DURATION		7
END

RECORD	SNIPER2F
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	1
	DURATION		7
END

RECORD	SNIPER2L
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	1
	DURATION		7
END

RECORD	SNIPER3F
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	1
	DURATION		3
END

RECORD	SNIPER3L
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 	1
	DURATION		3
END