# LevelSetup.ini
#
# Stores various values that need to be define at the start of each level.
# E.g. fog parameters, weather etc.
# Fog types: LINEAR, EXP, EXP2
#
# Note: these values are assigned in order - the number in the record header is ignored!!!!!!!!

RECORD world1
	FOG_COLOUR		0,0,0,0
	FOG_TYPE		LINEAR
	FOG_DENSITY		0.01
	NEAR_CLIP		0.1
	FAR_CLIP		120.0
	AMBIENT			0, 0, 0, 0
END

####################################################################################################
RECORD CLOUDY
	AVOID
END
####################################################################################################
RECORD WINDY
	AVOID
END
###################################################################################################
RECORD RAINY
	AVOID
END
####################################################################################################
RECORD THUNDERSTORM
	AVOID
END
####################################################################################################
RECORD FOGGY
	AVOID
END
####################################################################################################
RECORD CLEAR
	FARCLIP 	120.0f
	FOGSTART	100.0f
	SKY		2,2,5
	CLOUDS		2,2,5
END
####################################################################################################
RECORD ARTFILTER
	ARTFILTERRAD_INDOORS		0.002f
	ARTFILTER_INDOORS		40,45,40
	ARTFILTERRAD_CLOUDY		0.002f
	ARTFILTER_CLOUDY		40,45,40
	ARTFILTERRAD_RAINY		0.002f
	ARTFILTER_RAINY			40,45,40
	ARTFILTERRAD_FOGGY		0.002f
	ARTFILTER_FOGGY			40,45,40
	ARTFILTERRAD_CLEAR		0.002f
	ARTFILTER_CLEAR			40,45,40
END


# this space is intentionally left blank!


