#####################################################################################################
# SPLINE LEVEL SETUP FILE - Created by Derek Ward.
#
# Splines loaded for a level are put in here, with setting for the type of spline, and its duration.
#
# The RECORD name should tie up with a filename in your level\spl\directory
# However you should not add .spl to the end of the filename!
#
# The default duration can be specified here for testing, but this can be overridden permentantly by 
# a script if not 0.0f.
#
#####################################################################################################

# Put comments here to describe what the spline does or is intended for.
#STARTCODE <--- NEVER REMOVE THIS AS THIS INDICATES WHERE A SPLINE FILE SHOULD START FOR BINARTY CONCATENATION.
RECORD	FOLLOW1
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		4.0
END

RECORD	LOOKAT1
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		4.0
END
RECORD	FOLLOW2
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		8.0
END

RECORD	LOOKAT2
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		8.0
END
RECORD	FOLLOW4
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		4.0
END

RECORD	LOOKAT4
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		4.0
END
RECORD	FOLLOW3
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		2.0
END

RECORD	LOOKAT3
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		2.0
END
RECORD	FOLLOW5
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		6.0
END

RECORD	LOOKAT5
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		6.0
END
RECORD	FOLLOW6
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		2.5
END

RECORD	LOOKAT6
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		2.5
END
RECORD	FOLLOW7
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		16.0
END

RECORD	LOOKAT7
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		16.0
END
RECORD	FOLLOW8
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		4.0
END

RECORD	LOOKAT8
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		4.0
END
RECORD	FOLLOW9
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		5.0
END

RECORD	LOOKAT9
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		5.0
END
RECORD	FOLLOW10
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		10.0
END

RECORD	LOOKAT10
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		10.0
END
RECORD	FOLLOW11
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		6.0
END

RECORD	LOOKAT11
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		6.0
END
RECORD	FOLLOW21
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		6.0
END

RECORD	LOOKAT21
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		6.0
END
RECORD	FOLLOW22
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		7.0
END

RECORD	LOOKAT22
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		6.0
END
RECORD	FOLLOW23
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		6.0
END

RECORD	LOOKAT23
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		6.0
END
RECORD	FOLLOW24
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		14.0
END

RECORD	LOOKAT24
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		14.0
END
RECORD	FOLLOW31
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		14.0
END

RECORD	LOOKAT31
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		14.0
END
RECORD	FOLLOW32
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		5.0
END

RECORD	LOOKAT32
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		5.0
END
RECORD	FOLLOW33
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		5.0
END

RECORD	LOOKAT33
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		5.0
END
RECORD	FOLLOW34
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		9.0
END

RECORD	LOOKAT34
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		9.0
END
RECORD	FOLLOW35
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		5.0
END

RECORD	LOOKAT35
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		5.0
END
RECORD	FOLLOW36
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		5.0
END

RECORD	LOOKAT36
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		5.0
END
RECORD	FOLLOW37
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		23.0
END

RECORD	LOOKAT37
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		23.0
END
RECORD	FOLLOW38
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		10.0
END

RECORD	LOOKAT38
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		10.0
END
RECORD	FOLLOW39
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		7.0
END

RECORD	LOOKAT39
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		7.0
END
RECORD	FOLLOW41
	ISFOLLOW		1
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		20.0
END

RECORD	LOOKAT41
	ISFOLLOW		0
	ISSMOOTH		1
	ISALIGNEDFOLLOWPATH 0
	DURATION		20.0
END



 
